# Generated by Django 5.1.4 on 2024-12-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_main_images/', verbose_name='Основное изображение'),
        ),
    ]
